export const getGplxHoanColumns = (pagination) => [
    {
        title: "STT",
        key: "index",
        width: 60,
        align: "center",
        render: (text, record, index) => (pagination.page - 1) * pagination.limit + index + 1,
    },
    {
        title: "Số GPLX",
        dataIndex: "so_gplx",
        key: "so_gplx",
        align: "center",
        render: (val) => val || "—",
    },
    {
        title: "Họ và tên",
        dataIndex: "ho_ten",
        key: "ho_ten",
        sorter: (a, b) => (a.ho_ten || "").localeCompare(b.ho_ten || ""),
    },
    {
        title: "Ngày sinh",
        dataIndex: "ngay_sinh",
        key: "ngay_sinh",
        align: "center",
        width: 110,
        render: (val) => val || "—",
    },
    {
        title: "Hạng",
        dataIndex: "hang",
        key: "hang",
        align: "center",
        width: 80,
        render: (val) => val || "—",
    },
    {
        title: "Ngày cấp",
        dataIndex: "ngay_cap",
        key: "ngay_cap",
        align: "center",
        width: 110,
        render: (val) => val || "—",
    },
    {
        title: "Thời hạn",
        dataIndex: "thoi_han",
        key: "thoi_han",
        align: "center",
        width: 130,
        render: (val) => val || "—",
    },
    {
        title: "Địa chỉ",
        dataIndex: "dia_chi",
        key: "dia_chi",
        render: (val) => val || "—",
    },
    {
        title: "Đầu mối",
        dataIndex: "dau_moi",
        key: "dau_moi",
        render: (val) => val || "—",
    },
];
